services:

  ansible:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    command: bash
    tty: true
    environment:
      ANSIBLE_USER_SSH_PUBLIC_KEY: $ANSIBLE_USER_SSH_PUBLIC_KEY
    volumes:
      - './project:/home/ansible/project'