name: Generate Ansible Inventory

on:
  workflow_call:

jobs:
  build-inventory:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Set lower case owner name
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Build CDK Docker image
        working-directory: terraform-inventory
        run: |
          docker build -t ghcr.io/${{ env.OWNER_LC }}/terraform-inventory:latest -f Dockerfile .

      - name: Push CDK Docker image
        run: docker push ghcr.io/${{ env.OWNER_LC }}/terraform-inventory:latest
