name: Build CDK Docker Image

on:
  workflow_call:
    inputs:
      owner_lc:
        required: true
        type: string
      repo_url:
        required: true
        type: string
        
jobs:
  build-cdk-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: cdk-backend
          file: cdk-backend/Dockerfile
          push: true
          tags: ghcr.io/${{ inputs.owner_lc }}/cdk-backend:latest
          provenance: false
          build-args: |
            OWNER_LC=${{ inputs.owner_lc }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ inputs.owner_lc }}/${{ github.repository }}
