name: Generate Ansible Inventory

on:
  workflow_call:
    inputs:
      owner_lc:
        required: true
        type: string  

jobs:
  generate-inventory:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ inputs.owner_lc }}/terraform-inventory:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}     
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}         
    steps:

      - name: Download Terraform State from S3
        working-directory: /app
        run: |
          aws s3 cp s3://terraform-culturedevops/terraform.tfstate terraform.tfstate

      - name: Generate Ansible Inventory
        working-directory: /app
        run: python terraform_inventory.py terraform.tfstate inventory.ini

      - name: Upload Inventory
        uses: actions/upload-artifact@v4
        with:
          name: ansible-inventory
          path: /app/inventory.ini
