name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      owner_lc: ${{ steps.set-owner-lc.outputs.owner_lc }} 
      repo_url: ${{ github.repository }}
    steps:
      - name: Set lower case owner name
        id: set-owner-lc
        run: echo "owner_lc=${OWNER,,}" >> "$GITHUB_OUTPUT"
        env:
          OWNER: ${{ github.repository_owner }}
      - name: Set repository URL
        id: set-repo-url
        run: echo "REPO_URL=${{ github.repository }}" >> $GITHUB_ENV          
          
  build-cdk:
    uses: ./.github/workflows/build-cdk.yml
    needs: set-env
    with:
      owner_lc: ${{ needs.set-env.outputs.owner_lc }}    
      repo_url: ${{ needs.set-env.outputs.repo_url }}
    secrets: inherit    
    # if: |
    #   github.event.head_commit.modified && (
    #     'cdk-backend/**' in github.event.head_commit.modified
    #   )           
  
  build-inventory:
    uses: ./.github/workflows/build-inventory.yml    
    needs: set-env
    with:
      owner_lc: ${{ needs.set-env.outputs.owner_lc }}     
      repo_url: ${{ needs.set-env.outputs.repo_url }}
    secrets: inherit       

  build-debops:
    uses: ./.github/workflows/build-debops.yml
    needs: set-env
    with:
      owner_lc: ${{ needs.set-env.outputs.owner_lc }}     
      repo_url: ${{ needs.set-env.outputs.repo_url }}
    secrets: inherit
    # if: |
    #   github.event.head_commit.modified && (
    #     'ansible/Dockerfile' in github.event.head_commit.modified
    #   )

  deploy-cdk:
    uses: ./.github/workflows/deploy-cdk.yml
    needs: set-env
    with:
      owner_lc: ${{ needs.set-env.outputs.owner_lc }}     
    secrets: inherit      

  terraform:
    uses: ./.github/workflows/terraform.yml
    needs: deploy-cdk

  generate-inventory:
    uses: ./.github/workflows/generate-inventory.yml
    needs: [terraform,set-env]
    with:
      owner_lc: ${{ needs.set-env.outputs.owner_lc }}      

  run-debops:
    uses: ./.github/workflows/run-debops.yml
    needs: [generate-inventory,set-env]
    with:
      owner_lc: ${{ needs.set-env.outputs.owner_lc }}      
