name: Deploy Pipeline

on:
  push:
    branches:
      - main
    # paths:
    #   - cdk-backend/**
    #   - terraform-inventory/**
    #   - ansible/Dockerfile

jobs:
  show-token:
    runs-on: ubuntu-latest   
    steps:  
      - name: Show GHCR_TOKEN
        run: echo "GHCR_TOKEN=${{ vars.GHCR_TOKEN }}"
  build-cdk:
    uses: ./.github/workflows/build-cdk.yml
    # if: |
    #   github.event.head_commit.modified && (
    #     'cdk-backend/**' in github.event.head_commit.modified
    #   )           
  
  build-inventory:
    uses: ./.github/workflows/build-inventory.yml           

  build-debops:
    uses: ./.github/workflows/build-debops.yml
    # if: |
    #   github.event.head_commit.modified && (
    #     'ansible/Dockerfile' in github.event.head_commit.modified
    #   )

  deploy-cdk:
    uses: ./.github/workflows/deploy-cdk.yml

  terraform:
    uses: ./.github/workflows/terraform.yml
    needs: deploy-cdk

  generate-inventory:
    uses: ./.github/workflows/generate-inventory.yml
    needs: terraform

  run-debops:
    uses: ./.github/workflows/run-debops.yml
    needs: generate-inventory
