name: Run DebOps Bootstrap

on:
  workflow_call:
    inputs:
      owner_lc:
        required: true
        type: string

jobs:
  debops:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ inputs.owner_lc }}/ansible:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}      
      env:
         ANSIBLE_USER_SSH_PUBLIC_KEY: ${{ secrets.ANSIBLE_USER_SSH_PUBLIC_KEY }}
         ANSIBLE_CONFIG: ./ansible.cfg
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH agent
        working-directory: ansible/project
        run: |
          # Start the SSH agent
          eval $(ssh-agent -s)
          # Add the SSH private key to the agent
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

      - name: Download Inventory Artifact
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory

      - name: Install packages
        working-directory: ansible/project
        run: |
            apt-get update -y && apt-get install -y openssh-client git \
                python3-future python3-ldap python3-netaddr \
                python3-dnspython python3-passlib python3-toml \
                build-essential python3-dev libffi-dev libssl-dev \
                libsasl2-dev libldap2-dev python3-pip \
                unzip python3-setuptools curl jq
            pip3 install --upgrade debops[ansible]
            PATH=$PATH:$HOME/.local/bin
            pip3 show debops

      - name: Move Inventory File      
        run: |
          ls -l 
          pwd
          cat inventory.ini
          mv inventory.ini ansible/project/ansible/inventory/hosts

      - name: Prepare Ansible Configurations
        working-directory: ansible/project
        run: |
          bash add_known_hosts.sh

      - name: Run Ansible Bootstrap
        working-directory: ansible/project
        run: |
          pwd
          pip3 show debops
          which debops
          ls -la /__w/aws-cdk-terraform-ansible/aws-cdk-terraform-ansible/
          debops run bootstrap -l amazon
