name: Run DebOps Bootstrap

on:
  workflow_call:
    inputs:
      owner_lc:
        required: true
        type: string

jobs:
  debops:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ inputs.owner_lc }}/ansible:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}      
      env:
         ANSIBLE_USER_SSH_PUBLIC_KEY: ${{ secrets.ANSIBLE_USER_SSH_PUBLIC_KEY }}
         ANSIBLE_CONFIG: ./ansible.cfg
    steps:
      # - uses: actions/checkout@v4

      - name: Set up SSH agent
        working-directory: /home/ansible/project
        run: |
          # Start the SSH agent
          eval $(ssh-agent -s)
          # Add the SSH private key to the agent
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

      - name: Download Inventory Artifact
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory

      # - name: Get Inventory Artifact URL
      #   run: |
      #     ARTIFACT_URL=$(curl -s -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
      #       "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
      #       jq -r '.artifacts[] | select(.name=="ansible-inventory").archive_download_url')

      #     echo "Download URL: $ARTIFACT_URL"
      #     echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV

      # - name: Download and Extract Inventory
      #   run: |
      #     curl -s -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o /home/ansible/ansible-inventory.zip \
      #       "$ARTIFACT_URL"

      #     unzip -o /home/ansible/ansible-inventory.zip -d /home/ansible/

      - name: Move Inventory File      
        run: |
          ls -l 
          pwd
          cat inventory.ini
          mv inventory.ini /home/ansible/project/ansible/inventory/hosts

      - name: Prepare Ansible Configurations
        working-directory: /home/ansible/project
        run: |
          bash add_known_hosts.sh

      - name: Run Ansible Bootstrap
        working-directory: /home/ansible/project
        run: |
          ls -la
          pwd
          pip3 show debops
          which debops
          debops run bootstrap -l amazon
