name: Run DebOps Bootstrap

on:
  workflow_call:
    inputs:
      owner_lc:
        required: true
        type: string

jobs:
  debops:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ inputs.owner_lc }}/ansible:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}      
      env:
         ANSIBLE_USER_SSH_PUBLIC_KEY: ${{ secrets.ANSIBLE_USER_SSH_PUBLIC_KEY }}
         ANSIBLE_CONFIG: ./ansible.cfg
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH agent
        run: |
          mkdir -p /root/.ssh
          chmod 700 /root/.ssh        
          # Start the SSH agen
          eval $(ssh-agent -s)
          # Add the SSH private key to the agent
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa
          ssh-add /root/.ssh/id_rsa
          head -n 10 /root/.ssh/id_rsa

      - name: Download Inventory Artifact
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory

      - name: Move Inventory File      
        run: |
          mv inventory.ini ansible/project/ansible/inventory/hosts

      - name: Prepare Ansible Configurations
        working-directory: ansible/project
        run: |
          bash add_known_hosts.sh

      - name: Display known_hosts
        run: cat /root/.ssh/known_hosts

      - name: Install DebOps
        run: |
          pip3 install --upgrade debops[ansible]
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          debops --version

      - name: Debug DebOps Files
        run: |
          echo "Checking DebOps paths..."
          debops config get
          debops config list
          find $HOME -type d -name "debops" 2>/dev/null

      - name: Ensure DebOps Roles and Playbooks Are Installed
        run: |
          ansible-galaxy collection install debops.debops --force          

      - name: Run Ansible Bootstrap
        working-directory: ansible/project
        env:
          ANSIBLE_FORCE_COLOR: 'true'        
        run: |
          debops run bootstrap -l amazon

      - name: Run Ansible Site
        working-directory: ansible/project
        env:
          ANSIBLE_FORCE_COLOR: 'true'        
        run: |
          debops run site -l amazon