name: Run DebOps Bootstrap

on:
  workflow_call:
    inputs:
      owner_lc:
        required: true
        type: string

jobs:
  debops:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ inputs.owner_lc }}/ansible:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}      
      env:
         ANSIBLE_USER_SSH_PUBLIC_KEY: ${{ secrets.ANSIBLE_USER_SSH_PUBLIC_KEY }}
         ANSIBLE_CONFIG: ./ansible.cfg
         PATH: /home/runner/.local/bin:$PATH
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH agent
        working-directory: /home/ansible/project
        run: |
          # Start the SSH agent
          eval $(ssh-agent -s)
          # Add the SSH private key to the agent
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

      - name: Download Inventory Artifact
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory

      - name: Move Inventory File      
        run: |
          mv inventory.ini ansible/project/ansible/inventory/hosts

      - name: Prepare Ansible Configurations
        working-directory: ansible/project
        run: |
          bash add_known_hosts.sh

      - name: Install DebOps
        run: |
          pip3 install --upgrade debops[ansible]
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          debops --version

      - name: Run Ansible Bootstrap
        working-directory: ansible/project
        run: |
          debops run bootstrap -l amazon
