name: Run DebOps Bootstrap

on:
  workflow_call:
    inputs:
      owner_lc:
        required: true
        type: string

jobs:
  debops:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ inputs.owner_lc }}/debops:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}      
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

      - name: Prepare Ansible Configurations
        run: |
          export ANSIBLE_CONFIG=./ansible.cfg
          export ANSIBLE_USER_SSH_PUBLIC_KEY=${{ secrets.ANSIBLE_USER_SSH_PUBLIC_KEY }}
          bash add_known_hosts.sh

      - name: Download Inventory
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory

      - name: Move Inventory File      
        run: mv inventory.ini /home/ansible/project/ansible/inventory/hosts

      - name: Run Ansible Bootstrap
        working-directory: /home/ansible/project
        run: debops run bootstrap -i ansible/hosts -l amazon -e 'ansible_user=admin'
