name: Run DebOps Bootstrap

on:
  workflow_call:
    inputs:
      owner_lc:
        required: true
        type: string

jobs:
  debops:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ inputs.owner_lc }}/ansible:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}      
      env:
         ANSIBLE_USER_SSH_PUBLIC_KEY: ${{ secrets.ANSIBLE_USER_SSH_PUBLIC_KEY }}
    steps:

      - name: Set up SSH agent
        run: |
          # Start the SSH agent
          eval $(ssh-agent -s)
          # Add the SSH private key to the agent
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

      - name: Download Inventory
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory
          path: /home/ansible

      - name: Move Inventory File      
        run: mv /home/ansible/inventory.ini /home/ansible/project/ansible/inventory/hosts

      - name: Prepare Ansible Configurations
        working-directory: /home/ansible/project
        run: |
          bash add_known_hosts.sh

      - name: Run Ansible Bootstrap
        working-directory: /home/ansible/project
        run: ls ~/.local/share/debops/ansible/playbooks/ && debops run bootstrap -i ansible/hosts -l amazon -e 'ansible_user=admin'
