name: Run DebOps Bootstrap

on:
  workflow_call:
    inputs:
      owner_lc:
        required: true
        type: string

jobs:
  debops:
    runs-on: ubuntu-22.04
    env:
      ANSIBLE_USER_SSH_PUBLIC_KEY: ${{ secrets.ANSIBLE_USER_SSH_PUBLIC_KEY }}
      ANSIBLE_CONFIG: ./ansible.cfg
      # PATH: /home/runner/.local/bin:$PATH

    steps:
      - name: Check if running inside a container
        run: |
          if [ -f /.dockerenv ]; then
            echo "Running inside a Docker container!"
          else
            echo "Running on a full VM."
          fi    
      - name: Debug OS
        run: |
          echo "OS Information:"
          uname -a
          cat /etc/os-release || true
          echo "Available package managers:"
          which apt || echo "apt not found"
          which apt-get || echo "apt-get not found"
          which dnf || echo "dnf not found"
          which yum || echo "yum not found"
          which apk || echo "apk not found"          
      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-client git \
            python3-future python3-ldap python3-netaddr \
            python3-dnspython python3-passlib python3-toml \
            build-essential python3-dev libffi-dev libssl-dev \
            libsasl2-dev libldap2-dev python3-pip tar

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install DebOps
        run: |
          pip3 install --user --upgrade debops[ansible]
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          debops --version

      - name: Set up SSH agent
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

      - name: Download Inventory Artifact
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory

      - name: Move Inventory File      
        run: |
          ls -l
          pwd
          cat inventory.ini
          mkdir -p ./ansible/inventory/
          mv inventory.ini ./ansible/inventory/hosts

      - name: Prepare Ansible Configurations
        run: |
          bash add_known_hosts.sh

      - name: Run Ansible Bootstrap
        run: |
          which debops
          debops run bootstrap -l amazon
