name: Run DebOps Bootstrap

on:
  workflow_call:
    inputs:
      owner_lc:
        required: true
        type: string

jobs:
  debops:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ inputs.owner_lc }}/ansible:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}      
      env:
         ANSIBLE_USER_SSH_PUBLIC_KEY: ${{ secrets.ANSIBLE_USER_SSH_PUBLIC_KEY }}
    steps:

      - name: Set up SSH agent
        working-directory: /home/ansible/project
        run: |
          # Start the SSH agent
          eval $(ssh-agent -s)
          # Add the SSH private key to the agent
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          touch test_file
          ls -la

      - name: Download Inventory using GitHub API
        run: |
          echo "Download URL: $(curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq -r '.artifacts[0].archive_download_url')"        
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
            jq -r '.artifacts[0].archive_download_url' | \
            xargs -I {} curl -L -o /home/ansible/ansible-inventory.zip {}
        
      - name: Unzip Inventory File
        run: |
          head -n 10 /home/ansible/ansible-inventory.zip
          unzip /home/ansible/ansible-inventory.zip -d /home/ansible/

      - name: Move Inventory File      
        run: cp /home/ansible/inventory.ini /home/ansible/project/ansible/inventory/hosts

      - name: Prepare Ansible Configurations
        working-directory: /home/ansible/project
        run: |
          bash add_known_hosts.sh

      - name: Run Ansible Bootstrap
        working-directory: /home/ansible/project
        run: |
          debops run bootstrap -i ansible/hosts -l amazon -e 'ansible_user=admin'
