name: Run DebOps Bootstrap

on:
  workflow_call:
    inputs:
      owner_lc:
        required: true
        type: string

jobs:
  debops:
    runs-on: ubuntu-22.04
    env:
      ANSIBLE_USER_SSH_PUBLIC_KEY: ${{ secrets.ANSIBLE_USER_SSH_PUBLIC_KEY }}
      ANSIBLE_CONFIG: ./ansible.cfg
      # PATH: /home/runner/.local/bin:$PATH

    steps:
    
      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-client git \
            python3-future python3-ldap python3-netaddr \
            python3-dnspython python3-passlib python3-toml \
            build-essential python3-dev libffi-dev libssl-dev \
            libsasl2-dev libldap2-dev python3-pip tar

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install DebOps
        run: |
          pip3 install --upgrade debops[ansible]
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          debops --version

      - name: Set up SSH agent
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

      - name: Download Inventory Artifact
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory

      - name: Move Inventory File      
        run: |
          mv inventory.ini ./ansible/project/ansible/inventory/hosts

      - name: Prepare Ansible Configurations
        working-directory: ansible/project
        run: |
          pwd
          ls -la
          bash add_known_hosts.sh

      - name: Debug DebOps Files
        run: |
          echo "Checking DebOps paths..."
          debops config get
          debops config list
          find $HOME -type d -name "debops" 2>/dev/null

      - name: Ensure DebOps Roles and Playbooks Are Installed
        run: |
          ansible-galaxy collection install debops.debops --force

      # - name: Debug DebOps Installation
      #   run: |
      #     echo "Checking DebOps installation..."
      #     find $HOME/.local/share/debops -type f | head -n 20
      #     find ~/.ansible/collections/ansible_collections/debops -type f | head -n 20

      - name: Run Ansible Bootstrap
        working-directory: ansible/project
        run: |  
          debops run bootstrap -l amazon
