name: Run DebOps Bootstrap

on:
  workflow_call:
    inputs:
      owner_lc:
        required: true
        type: string

jobs:
  debops:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ inputs.owner_lc }}/ansible:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}      
      env:
        ANSIBLE_USER_SSH_PUBLIC_KEY: ${{ secrets.ANSIBLE_USER_SSH_PUBLIC_KEY }}

    steps:

      - name: Set up SSH agent
        working-directory: /home/ansible/project
        run: |
          # Start the SSH agent
          eval $(ssh-agent -s)
          # Add the SSH private key to the agent
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get artifact download URL
        run: |
          asset=$(gh api /repos/${{ github.repository }}/actions/artifacts --jq ".artifacts[0].archive_download_url")
          echo "Download URL: $asset"

      - name: Download artifact
        run: |
          curl -L -o /home/ansible/ansible-inventory.zip "$asset" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
        
      - name: Unzip Inventory File
        run: |
          head -n 10 /home/ansible/ansible-inventory.zip
          unzip /home/ansible/ansible-inventory.zip -d /home/ansible/

      - name: Move Inventory File      
        run: cp /home/ansible/inventory.ini /home/ansible/project/ansible/inventory/hosts

      - name: Prepare Ansible Configurations
        working-directory: /home/ansible/project
        run: |
          bash add_known_hosts.sh

      - name: Run Ansible Bootstrap
        working-directory: /home/ansible/project
        run: |
          debops run bootstrap -i ansible/hosts -l amazon -e 'ansible_user=admin'
