name: Create EC2 Instances

on:
  workflow_call:

jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.AWS_SECRET_ACCESS_KEY }}   
        TF_VAR_vpc_id: ${{ vars.TF_VAR_VPC_ID }}
        TF_VAR_ssh_key_name: ${{ vars.TF_VAR_SSH_KEY_NAME }}  
        TF_VAR_s3_bucket_name: ${{ vars.TF_VAR_S3_BUCKET_NAME }}  
        TF_VAR_vm_count: ${{ vars.TF_VAR_VM_COUNT }}  
    steps:
      - uses: actions/checkout@v4

      - name: Initialize Terraform
        working-directory: terraform/project
        run: terraform init -backend-config="bucket=${{ vars.TF_VAR_S3_BUCKET_NAME }}"

      - name: Apply Terraform
        working-directory: terraform/project
        run: terraform apply -auto-approve
